/*******************************************************************
	NAME:	DEFAULT
	DESC:	Denne kode finder defaulted kunder og deres tilhørende virksomhed,
            hvis dette eksistere

			Det er blevet besluttet at et default_flag = 1 bliver overført til del_modparten og
			og dens tilhørende kundenr, for I/S, og EMV K/S. Dette er dog ikke gældende 
			for HOLDING, APS og A/S.    
*******************************************************************/

cas mySession sessopts=(timeout=3500000);
caslib _all_ assign;
options casdatalimit=500M;

%LET START_PERIODAG = 2022-01-01; 
%LET SLUT_PERIODAG = 2022-12-31; 

%LET SQL_START_PERIODAG=%STR(%')&START_PERIODAG.%STR(%');
%LET SQL_SLUT_PERIODAG=%STR(%')&SLUT_PERIODAG.%STR(%');


PROC FEDSQL SESSREF=mySession;
drop table CASUSER.RELATIONER_FULD FORCE;
CREATE TABLE CASUSER.RELATIONER_FULD AS SELECT 
DAG.DATO
,REL.*
FROM (SELECT DATO FROM RAT_DATA.DAGE 

WHERE DATO < &SQL_SLUT_PERIODAG. and &SQL_START_PERIODAG. <DATO 
)
AS DAG

INNER JOIN (
SELECT 
KUNDENR
,NAVN
,CVRNR
,VIRKSOMHEDSNAVN
,SLSKFORM
,DB07
,EJERFORHOLD
,EJERFORHOLD_TXT
,EJERANDELPCT
,ENGAGEMENT_KREDIT_VIRKSOMHED
,ANTAL_EJERE
,START_DATO
,SLUT_DATO


FROM RAT_DATA.RELATIONER 

WHERE START_DATO < &SQL_SLUT_PERIODAG. AND &SQL_START_PERIODAG. <SLUT_DATO 
	  AND (ENGAGEMENT_KREDIT_VIRKSOMHED=. OR ENGAGEMENT_KREDIT_VIRKSOMHED<=250000 )
)
AS REL
/* ON DAG.DATO between REL.START_DATO and REL.SLUT_DATO-1 */
ON REL.START_DATO<= DAG.DATO AND DAG.DATO<REL.SLUT_DATO
;
QUIT; 



PROC FEDSQL SESSREF=mySession;
drop table CASUSER.DEFAULT_DAGLIG FORCE;
CREATE TABLE CASUSER.DEFAULT_DAGLIG AS SELECT 
DAG.DATO
,DEF.KUNDENR
,DEF.MODPARTS_ID
,DEF.DEL_MODPARTS_ID
,DEF.DEFAULT_FLAG
,DEF.ANTAL_DEF
,DEF.ANTAL_MDR_DEF
,DEF.PERIODE_START
,DEF.PERIODE_SLUT
,DEF.START_DATO
,DEF.SLUT_DATO

FROM (SELECT DATO FROM RAT_DATA.DAGE 

WHERE DATO < &SQL_SLUT_PERIODAG. and &SQL_START_PERIODAG. <DATO 
)
AS DAG

INNER JOIN (
SELECT 
KUNDENR
,MODPARTS_ID
,DEL_MODPARTS_ID
,DEFAULT_FLAG
,ANTAL_DEF
,ANTAL_MDR_DEF
,PERIODE_START
,PERIODE_SLUT
,START_DATO
,SLUT_DATO

FROM RAT_DATA.DEFAULT_DATA

WHERE START_DATO < &SQL_SLUT_PERIODAG. and &SQL_START_PERIODAG. <SLUT_DATO 
)
AS DEF

ON DEF.START_DATO <= DAG.DATO AND DAG.DATO < DEF.SLUT_DATO
;
QUIT; 

/* TJEKKER OM VIRKSOMHEDEN HAR DEFAULT_FLAG = 1 OG DANNER NY 0/1 VARIABLE DEFAULT_VIRK */
PROC FEDSQL SESSREF=mySession;
drop table CASUSER.DEFAULT_VIRKSOMHED FORCE;
CREATE TABLE CASUSER.DEFAULT_VIRKSOMHED AS SELECT 
REL.KUNDENR
,DEF.MODPARTS_ID
,DEF.DEL_MODPARTS_ID
,REL.DATO
,REL.CVRNR
,REL.EJERFORHOLD
,REL.EJERFORHOLD_TXT
,REL.ANTAL_EJERE
,DEF.ANTAL_DEF
,DEF.ANTAL_MDR_DEF
,DEF.PERIODE_START
,DEF.PERIODE_SLUT
,DEF.SLUT_DATO
,DEF.START_DATO
,DEF.DEFAULT_FLAG AS DEFAULT_VIRK

FROM CASUSER.RELATIONER_FULD AS REL

LEFT JOIN DEFAULT_DAGLIG AS DEF
ON REL.CVRNR=DEF.KUNDENR AND REL.DATO=DEF.DATO

HAVING DEFAULT_FLAG = 1 
;
QUIT; 


/* SAMMENSÆTTER ORIGNAL DEFAULT DATASÆT MED DEFAULT FOR VIRKSOMHEDER */
DATA CASUSER.DEFAULT_TOTAL  ( REPLACE=yes); 
SET CASUSER.DEFAULT_DAGLIG CASUSER.DEFAULT_VIRKSOMHED; 
RUN; 



/* FINDER DEL_MODPARTS_ID FOR HVERT KUNDENR, FOR AT FINDE EJER/PARNTER FORHOLD */
PROC FEDSQL SESSREF=mySession;
drop table CASUSER.DEFAULT_DELMOD FORCE;
CREATE TABLE CASUSER.DEFAULT_DELMOD AS SELECT 
DEF.KUNDENR AS KUNDENR_ORG 
,STAM.DEL_MODPARTS_ID
,DEF.MODPARTS_ID
,DEF.DATO
,DEF.CVRNR
,DEF.EJERFORHOLD
,DEF.EJERFORHOLD_TXT
,DEF.ANTAL_EJERE
,DEF.ANTAL_DEF
,DEF.ANTAL_MDR_DEF
,DEF.PERIODE_START
,DEF.PERIODE_SLUT
,DEF.SLUT_DATO
,DEF.START_DATO
,DEF.DEFAULT_FLAG
,DEF.DEFAULT_VIRK

FROM (
SELECT 
KUNDENR
,DEL_MODPARTS_ID
,START_DATO
,SLUT_DATO 

FROM RAT_DATA.STAMOPLYSNINGER 
WHERE START_DATO < &SQL_SLUT_PERIODAG. AND &SQL_START_PERIODAG. <SLUT_DATO 
)
AS STAM

LEFT JOIN CASUSER.DEFAULT_TOTAL AS DEF
ON DEF.KUNDENR = STAM.KUNDENR AND STAM.START_DATO <= DEF.DATO AND DEF.DATO < STAM.SLUT_DATO
;
QUIT;



/* FOR HVERT DEL_MODPARTS_ID FINDES DE TILHØRENDE KUNDENR*/
PROC FEDSQL SESSREF=mySession;
drop table CASUSER.DEFAULT_DELMOD_ALLE FORCE;
CREATE TABLE CASUSER.DEFAULT_DELMOD_ALLE AS SELECT 
 STAM.KUNDENR  
,DEL.KUNDENR_ORG  
,DEL.DEL_MODPARTS_ID 
/* ,DEL.MODPARTS_ID  */
,DEL.CVRNR
,DEL.EJERFORHOLD
,DEL.EJERFORHOLD_TXT
,DEL.DEFAULT_FLAG
,DEL.DEFAULT_VIRK
,DEL.DATO
,DEL.START_DATO
,DEL.SLUT_DATO 
FROM DEFAULT_DELMOD AS DEL

LEFT JOIN (
SELECT 
KUNDENR
,DEL_MODPARTS_ID
,MODPARTS_ID
,START_DATO
, SLUT_DATO 

FROM RAT_DATA.STAMOPLYSNINGER 
WHERE START_DATO < &SQL_SLUT_PERIODAG. AND &SQL_START_PERIODAG. <SLUT_DATO 
)
AS STAM 
ON DEL.DEL_MODPARTS_ID = STAM.DEL_MODPARTS_ID AND STAM.START_DATO <= DEL.DATO AND DEL.DATO < STAM.SLUT_DATO

;
QUIT;

/* Overskriver default_flag for EMV, I/S og K/S - Det nye flag hedder default_flag_korr*/
PROC FEDSQL SESSREF=mySession;
DROP TABLE  CASUSER.DEFAULT_KORR_TEMP FORCE;
CREATE TABLE CASUSER.DEFAULT_KORR_TEMP  AS SELECT 
KUNDENR
,KUNDENR_ORG
,DEL_MODPARTS_ID
,MODPARTS_ID
,CVRNR
,DEFAULT_FLAG
,DEFAULT_VIRK
,DATO
,CASE 
/*EMV, I/S, K/S */
	WHEN (EJERFORHOLD in (31,32,33) AND DEFAULT_VIRK = 1 ) THEN 1 

/*A/S, APS, KA/S, HOLDING */
	WHEN EJERFORHOLD in (34,35,36,999) AND DEFAULT_VIRK = 1 THEN 0 

/* GENERELT*/
	WHEN DEFAULT_FLAG = 1 THEN 1

ELSE 0 END AS DEFAULT_FLAG_KORR  

FROM CASUSER.DEFAULT_DELMOD_ALLE
;
QUIT; 



PROC FEDSQL SESSREF=mySession;
DROP TABLE  CASUSER.DEFAULT_KORR_TEMP_MAX FORCE;
CREATE TABLE CASUSER.DEFAULT_KORR_TEMP_MAX  AS SELECT 
KUNDENR
,DEL_MODPARTS_ID
,MODPARTS_ID
,CVRNR
,DEFAULT_FLAG
,DEFAULT_VIRK
,DATO
,MAX(KUNDENR) as KUNDENRMAX

FROM CASUSER.DEFAULT_KORR_TEMP

GROUP BY 
KUNDENR
,DEL_MODPARTS_ID
,MODPARTS_ID
,CVRNR
,DEFAULT_FLAG
,DEFAULT_VIRK
,DATO
;
QUIT;









DATA CASUSER.DEFAULT_KORR ( REPLACE=yes DROP=DATO); 
SET CASUSER.DEFAULT_KORR_TEMP; 

WHERE DEFAULT_FLAG_KORR = 1;

START_DATO=DATO; 
SLUT_DATO=intnx('day',dato,+1); 
		
start_dttm=dhms(start_dato,0,0,0) ;
slut_dttm=dhms(SLUT_DATO,23,59,59)-86400  ;
format START_DATO SLUT_DATO DATE9. slut_dttm start_dttm datetime20. ;
RUN;

 %LET VIYA_LIBRARY=RAT_DATA;  
 %LET TABEL_NAVN=DEFAULT_KORR;  

 	proc casutil  incaslib="casuser" outcaslib="&VIYA_LIBRARY." ;     
 		save casdata="&TABEL_NAVN." replace;  
 		DROPTABLE CASDATA="&TABEL_NAVN." INCASLIB="&VIYA_LIBRARY." QUIET; 
 		load casdata="&TABEL_NAVN..sashdat"  
 		casout="&TABEL_NAVN." 	 
 		incaslib="&VIYA_LIBRARY."  promote; 
 	run;   




