/* cas mySession terminate; */

cas mySession sessopts=(timeout=3500000);
caslib _all_ assign;
options casdatalimit=20000M;

PROC SQL;
CREATE TABLE RAT_MODEL AS SELECT
DEFAULT_FLAG_KORR
,count(DEFAULT_FLAG_KORR) as count
FROM RM_MDL.RAT_DATA
GROUP BY DEFAULT_FLAG_KORR
;
QUIT;


PROC SQL;
CREATE TABLE privat_oko AS SELECT
DEFAULT_SAMLET
,count(DEFAULT_SAMLET) as count
FROM RM_MDL.PRIVAT_OKONOMI
GROUP BY DEFAULT_SAMLET
;
QUIT;



PROC SQL;
CREATE TABLE Rdefault_data_korr AS SELECT
DEFAULT_FLAG_KORR
,count(DEFAULT_FLAG_KORR) as count
FROM RAT_DATA.DEFAULT_DATA_KORR
GROUP BY DEFAULT_FLAG_KORR
;
QUIT;

PROC SQL;
CREATE TABLE privat_oko AS SELECT
DEFAULT_SAMLET
,count(DEFAULT_SAMLET) as count
FROM KKM.PRRE_DEFAULT
GROUP BY DEFAULT_SAMLET
;
QUIT;




PROC SQL;
CREATE TABLE okonomi AS SELECT
KUNDENR
,START_DATO
,SLUT_DATO
,GAELD
FROM RAT_DATA.OKONOMI_KORR
WHERE GAELD < 0 and GAELD NE . 
ORDER BY START_DATO
;
QUIT;
