cas mySession sessopts=(timeout=3500000);
caslib _all_ assign;
options casdatalimit=500M;

PROC FEDSQL SESSREF=MYSESSION;
drop table CASUSER.RELATIONER FORCE;
CREATE TABLE CASUSER.RELATIONER AS SELECT 
*
FROM RAT_DATA.RELATIONER

WHERE START_DATO <= '2022-02-01' and '2022-02-01' <SLUT_DATO 
;
QUIT; 

PROC FEDSQL SESSREF=MYSESSION;
drop table CASUSER.OVERTRAEK FORCE;
CREATE TABLE CASUSER.OVERTRAEK AS SELECT 
*
FROM RAT_DATA.OVERTRAEK

WHERE START_DATO <= '2022-02-01' and '2022-02-01' <SLUT_DATO 
;
QUIT; 

PROC FEDSQL SESSREF=MYSESSION;
drop table CASUSER.RELATIONER_NY FORCE;
CREATE TABLE CASUSER.RELATIONER_NY AS SELECT 
REL.*
,OVT.OVERTRK_BLB
,OVT.START_DATO AS START_DATO_OVT
,OVT.SLUT_DATO AS SLUT_DATO_OVT
FROM CASUSER.RELATIONER AS REL

LEFT JOIN CASUSER.OVERTRAEK AS OVT
ON REL.CVRNR=OVT.KUNDENR

;
QUIT; 

PROC FEDSQL SESSREF=MYSESSION;
drop table CASUSER.NYE_OVERTRAEK FORCE;
CREATE TABLE CASUSER.NYE_OVERTRAEK AS SELECT 
KUNDENR
,OVERTRK_BLB
,START_DATO_OVT
,SLUT_DATO_OVT
FROM CASUSER.RELATIONER_NY

WHERE OVERTRK_BLB>0
;
QUIT; 

DATA CASUSER.OVERTRAEK_TOTAL  ( REPLACE=yes); 
SET CASUSER.OVERTRAEK CASUSER.NYE_OVERTRAEK; 
RUN; 


PROC FEDSQL SESSREF=MYSESSION;
drop table CASUSER.OVERTRAEK_TOTAL FORCE;
CREATE TABLE CASUSER.OVERTRAEK_TOTAL AS SELECT 
KUNDENR
,SUM(OVERTRK_BLB) AS OVERTRK_BLB

FROM CASUSER.OVERTRAEK_TOTAL

GROUP BY KUNDENR ;
QUIT; 

