/*******************************************************************
	NAME:	RYKKER.sas
	DESC:	xxx   
******************************************************************/

cas mySession sessopts=(timeout=3500000);
caslib _all_ assign;
options casdatalimit=500M;

%LET START_PERIODAG = 2018-03-01;  
%LET SLUT_PERIODAG = 2023-01-31;  

%LET SQL_START_PERIODAG=%STR(%')&START_PERIODAG.%STR(%');
%LET SQL_SLUT_PERIODAG=%STR(%')&SLUT_PERIODAG.%STR(%');


PROC FEDSQL SESSREF=mySession;
drop table CASUSER.RELATIONER FORCE;
CREATE TABLE CASUSER.RELATIONER AS SELECT 
*
FROM RAT_DATA.RELATIONER

WHERE START_DATO < &SQL_SLUT_PERIODAG. and &SQL_START_PERIODAG. <SLUT_DATO 
;
QUIT; 


PROC FEDSQL SESSREF=mySession;
drop table CASUSER.DAGE FORCE;
CREATE TABLE CASUSER.DAGE AS SELECT 
*
FROM RAT_DATA.DAGE

WHERE DATO < &SQL_SLUT_PERIODAG. and &SQL_START_PERIODAG. <DATO 
;
QUIT; 

PROC FEDSQL SESSREF=mySession;
drop table CASUSER.RELATIONER_FULD FORCE;
CREATE TABLE CASUSER.RELATIONER_FULD AS SELECT 
DAG.DATO
,REL.*
FROM (SELECT DATO FROM RAT_DATA.DAGE 

WHERE DATO < &SQL_SLUT_PERIODAG. and &SQL_START_PERIODAG. <DATO 
)
AS DAG

INNER JOIN (
SELECT 
KUNDENR
,NAVN
,CVRNR
,VIRKSOMHEDSNAVN
,SLSKFORM
,DB07
,EJERANDELPCT
,ENGAGEMENT_KREDIT_VIRKSOMHED
,ANTAL_EJERE
,START_DATO
,SLUT_DATO


FROM RAT_DATA.RELATIONER 

WHERE START_DATO < &SQL_SLUT_PERIODAG. AND &SQL_START_PERIODAG. <SLUT_DATO 
	  AND (ENGAGEMENT_KREDIT_VIRKSOMHED=. OR ENGAGEMENT_KREDIT_VIRKSOMHED<=250000 )
)
AS REL
/* ON DAG.DATO between REL.START_DATO and REL.SLUT_DATO-1 */
ON REL.START_DATO<= DAG.DATO AND DAG.DATO<REL.SLUT_DATO
;
QUIT; 



PROC FEDSQL SESSREF=mySession;
drop table CASUSER.RYKKER_DAGLIG FORCE;
CREATE TABLE CASUSER.RYKKER_DAGLIG AS SELECT 
DAG.DATO
 ,RYK.KUNDENR 
 ,RYK.RYKKER_1_ANT 
 ,RYK.RYKKER_2_ANT 
 ,RYK.RYKKER_3_ANT 
 ,RYK.RYKKER_ANT  
 ,RYK.RYKKER_1_BELOB 
 ,RYK.RYKKER_2_BELOB 
 ,RYK.RYKKER_3_BELOB 
 ,RYK.RYKKER_BELOB 
FROM (SELECT DATO FROM RAT_DATA.DAGE 

WHERE DATO < &SQL_SLUT_PERIODAG. and &SQL_START_PERIODAG. <DATO 
)
AS DAG

INNER JOIN (
SELECT 
KUNDENR
 ,RYKKER_1_ANT 
 ,RYKKER_2_ANT 
 ,RYKKER_3_ANT 
 ,RYKKER_ANT 
 ,RYKKER_1_BELOB 
 ,RYKKER_2_BELOB 
 ,RYKKER_3_BELOB 
 ,RYKKER_BELOB 
,START_DATO
,SLUT_DATO

FROM RAT_DATA.RYKKER

WHERE START_DATO < &SQL_SLUT_PERIODAG. and &SQL_START_PERIODAG. <SLUT_DATO 
)
AS RYK
/* ON DAG.DATO between OVT.START_DATO and OVT.SLUT_DATO-1 */
ON RYK.START_DATO <= DAG.DATO AND DAG.DATO <= RYK.SLUT_DATO
;
QUIT; 

PROC FEDSQL SESSREF=mySession;
drop table CASUSER.RYKKER_OVERFOERT FORCE;
CREATE TABLE CASUSER.RYKKER_OVERFOERT AS SELECT 
REL.DATO
 ,REL.KUNDENR
 ,RYK.RYKKER_1_ANT 
 ,RYK.RYKKER_2_ANT 
 ,RYK.RYKKER_3_ANT 
 ,RYK.RYKKER_ANT  
 ,RYK.RYKKER_1_BELOB 
 ,RYK.RYKKER_2_BELOB 
 ,RYK.RYKKER_3_BELOB 
 ,RYK.RYKKER_BELOB 

FROM CASUSER.RELATIONER_FULD AS REL

LEFT JOIN CASUSER.RYKKER_DAGLIG AS RYK
ON REL.CVRNR=RYK.KUNDENR AND REL.DATO=RYK.DATO

HAVING RYKKER_BELOB > 0 /*RYKKER_1_ANT > 0 OR RYKKER_2_ANT > 0 OR RYKKER_3_ANT > 0 OR RYKKER_ANT > 0 
      OR RYKKER_1_BELOB > 0 OR RYKKER_2_BELOB > 0 OR RYKKER_3_BELOB > 0 */ 

;
QUIT; 

DATA CASUSER.RYKKER_TOTAL  ( REPLACE=yes); 
SET CASUSER.RYKKER_DAGLIG CASUSER.RYKKER_OVERFOERT; 
RUN; 

PROC FEDSQL SESSREF=mySession;
DROP TABLE  CASUSER.RYKKER_KORR FORCE;
CREATE TABLE CASUSER.RYKKER_KORR  AS SELECT 
KUNDENR
,DATO
,SUM(RYKKER_1_ANT)  AS RYKKER_1_ANT 
,SUM(RYKKER_2_ANT)  AS RYKKER_2_ANT 
,SUM(RYKKER_3_ANT)  AS RYKKER_3_ANT 
,SUM(RYKKER_ANT)  AS RYKKER_ANT 
,SUM(RYKKER_1_BELOB)  AS RYKKER_1_BELOB
,SUM(RYKKER_2_BELOB)  AS RYKKER_2_BELOB
,SUM(RYKKER_3_BELOB)  AS RYKKER_3_BELOB
,SUM(RYKKER_BELOB)  AS RYKKER_BELOB

FROM CASUSER.RYKKER_TOTAL

GROUP BY KUNDENR, DATO
;
QUIT; 

DATA CASUSER.RYKKER_KORR ( REPLACE=yes DROP=DATO); 
SET CASUSER.RYKKER_KORR; 

START_DATO=DATO; 
SLUT_DATO=intnx('day',dato,+1); 

		
start_dttm=dhms(start_dato,0,0,0) ;
slut_dttm=dhms(SLUT_DATO,23,59,59)-86400  ;
format START_DATO SLUT_DATO DATE9. slut_dttm start_dttm datetime20. ;
run;

%LET VIYA_LIBRARY=RAT_DATA; 
%LET TABEL_NAVN=RYKKER_KORR; 

	proc casutil  incaslib="casuser" outcaslib="&VIYA_LIBRARY." ;    
		save casdata="&TABEL_NAVN." replace; 
		DROPTABLE CASDATA="&TABEL_NAVN." INCASLIB="&VIYA_LIBRARY." QUIET;
		load casdata="&TABEL_NAVN..sashdat" 
		casout="&TABEL_NAVN." 	
		incaslib="&VIYA_LIBRARY."  promote;
	run;  


PROC FEDSQL SESSREF=mySession;
DROP TABLE CASUSER.DAGE FORCE;
DROP TABLE CASUSER.RELATIONER FORCE;
DROP TABLE CASUSER.RELATIONER_FULD FORCE;
DROP TABLE CASUSER.RYKKER_DAGLIG FORCE;
DROP TABLE CASUSER.RYKKER_KORR FORCE;
DROP TABLE CASUSER.RYKKER_OVERFOERT FORCE;
DROP TABLE CASUSER.RYKKER_TOTAL FORCE;
;
QUIT;

cas Mysession terminate;



