data &m_output_table_nm;
set &m_scoring_abt_table_nm;

*------------------------------------------------------------*;
* DABT JUDGEMENTAL SCORE CODE;
*------------------------------------------------------------*;

EM_SCORECARD_POINTS = 0;

*------------------------------------------------------------*;
* Variable: OVERFOERTRESULTAT_IALT_1;
*------------------------------------------------------------*;
if  NOT MISSING(OVERFOERTRESULTAT_IALT_1) then do;
if OVERFOERTRESULTAT_IALT_1 <-250 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_OVERFOERTRESULTAT_IALT_1 = 32430;
end;

else if OVERFOERTRESULTAT_IALT_1>=-250 and OVERFOERTRESULTAT_IALT_1<0 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 9 ;
GRP_OVERFOERTRESULTAT_IALT_1 = 32431;
end;

else if OVERFOERTRESULTAT_IALT_1>=0 and OVERFOERTRESULTAT_IALT_1<=0 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 16 ;
GRP_OVERFOERTRESULTAT_IALT_1 = 32432;
end;

else if OVERFOERTRESULTAT_IALT_1>0 and OVERFOERTRESULTAT_IALT_1<250 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 25 ;
GRP_OVERFOERTRESULTAT_IALT_1 = 32433;
end;

else if OVERFOERTRESULTAT_IALT_1 >=250 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 30 ;
GRP_OVERFOERTRESULTAT_IALT_1 = 32434;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 16 ;
GRP_OVERFOERTRESULTAT_IALT_1 = 32432;
end;
end;
else if MISSING(OVERFOERTRESULTAT_IALT_1) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 16 ;
GRP_OVERFOERTRESULTAT_IALT_1 = 32432;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 16 ;
GRP_OVERFOERTRESULTAT_IALT_1 = 32432;
end;


*------------------------------------------------------------*;
* Variable: EGENKAPITAL_IALT_1;
*------------------------------------------------------------*;
if  NOT MISSING(EGENKAPITAL_IALT_1) then do;
if EGENKAPITAL_IALT_1 <-800 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 643 ;
GRP_EGENKAPITAL_IALT_1 = 32410;
end;

else if EGENKAPITAL_IALT_1>=-800 and EGENKAPITAL_IALT_1<-400 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 658 ;
GRP_EGENKAPITAL_IALT_1 = 32411;
end;

else if EGENKAPITAL_IALT_1>=-400 and EGENKAPITAL_IALT_1<-200 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 661 ;
GRP_EGENKAPITAL_IALT_1 = 32412;
end;

else if EGENKAPITAL_IALT_1>=-200 and EGENKAPITAL_IALT_1<0 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 669 ;
GRP_EGENKAPITAL_IALT_1 = 32413;
end;

else if EGENKAPITAL_IALT_1>=0 and EGENKAPITAL_IALT_1<200 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 682 ;
GRP_EGENKAPITAL_IALT_1 = 32414;
end;

else if EGENKAPITAL_IALT_1 >=200 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 689 ;
GRP_EGENKAPITAL_IALT_1 = 32415;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 682 ;
GRP_EGENKAPITAL_IALT_1 = 32414;
end;
end;
else if MISSING(EGENKAPITAL_IALT_1) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 682 ;
GRP_EGENKAPITAL_IALT_1 = 32414;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 682 ;
GRP_EGENKAPITAL_IALT_1 = 32414;
end;


*------------------------------------------------------------*;
* Variable: EGENKAPITALENSFORRENTNING_1;
*------------------------------------------------------------*;
if  NOT MISSING(EGENKAPITALENSFORRENTNING_1) then do;
if EGENKAPITALENSFORRENTNING_1 <-50 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_EGENKAPITALENSFORRENTNING_1 = 32416;
end;

else if EGENKAPITALENSFORRENTNING_1>=-50 and EGENKAPITALENSFORRENTNING_1<-10 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 10 ;
GRP_EGENKAPITALENSFORRENTNING_1 = 32417;
end;

else if EGENKAPITALENSFORRENTNING_1>=-10 and EGENKAPITALENSFORRENTNING_1<=0 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 28 ;
GRP_EGENKAPITALENSFORRENTNING_1 = 32418;
end;

else if EGENKAPITALENSFORRENTNING_1>0 and EGENKAPITALENSFORRENTNING_1<15 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 43 ;
GRP_EGENKAPITALENSFORRENTNING_1 = 32419;
end;

else if EGENKAPITALENSFORRENTNING_1 >=15 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 47 ;
GRP_EGENKAPITALENSFORRENTNING_1 = 32420;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_EGENKAPITALENSFORRENTNING_1 = 32416;
end;
end;
else if MISSING(EGENKAPITALENSFORRENTNING_1) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_EGENKAPITALENSFORRENTNING_1 = 32416;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_EGENKAPITALENSFORRENTNING_1 = 32416;
end;


*------------------------------------------------------------*;
* Variable: SOLIDITETSGRAD_1;
*------------------------------------------------------------*;
if  NOT MISSING(SOLIDITETSGRAD_1) then do;
if SOLIDITETSGRAD_1 <-15 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_SOLIDITETSGRAD_1 = 32435;
end;

else if SOLIDITETSGRAD_1>=-15 and SOLIDITETSGRAD_1<0 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 3 ;
GRP_SOLIDITETSGRAD_1 = 32436;
end;

else if SOLIDITETSGRAD_1>=0 and SOLIDITETSGRAD_1<5 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 8 ;
GRP_SOLIDITETSGRAD_1 = 32437;
end;

else if SOLIDITETSGRAD_1>=5 and SOLIDITETSGRAD_1<15 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 23 ;
GRP_SOLIDITETSGRAD_1 = 32438;
end;

else if SOLIDITETSGRAD_1>=15 and SOLIDITETSGRAD_1<35 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 27 ;
GRP_SOLIDITETSGRAD_1 = 32439;
end;

else if SOLIDITETSGRAD_1>=35 and SOLIDITETSGRAD_1<70 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 47 ;
GRP_SOLIDITETSGRAD_1 = 32440;
end;

else if SOLIDITETSGRAD_1 >=70 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 65 ;
GRP_SOLIDITETSGRAD_1 = 32441;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_SOLIDITETSGRAD_1 = 32435;
end;
end;
else if MISSING(SOLIDITETSGRAD_1) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_SOLIDITETSGRAD_1 = 32435;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_SOLIDITETSGRAD_1 = 32435;
end;


*------------------------------------------------------------*;
* Variable: NETTOOMSAETNING_1_DELTA;
*------------------------------------------------------------*;
if  NOT MISSING(NETTOOMSAETNING_1_DELTA) then do;
if NETTOOMSAETNING_1_DELTA <-10 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 4 ;
GRP_NETTOOMSAETNING_1_DELTA = 32446;
end;

else if NETTOOMSAETNING_1_DELTA>=-10 and NETTOOMSAETNING_1_DELTA<=0 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 11 ;
GRP_NETTOOMSAETNING_1_DELTA = 32447;
end;

else if NETTOOMSAETNING_1_DELTA>0 and NETTOOMSAETNING_1_DELTA<10 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 33 ;
GRP_NETTOOMSAETNING_1_DELTA = 32448;
end;

else if NETTOOMSAETNING_1_DELTA>=10 and NETTOOMSAETNING_1_DELTA<20 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 17 ;
GRP_NETTOOMSAETNING_1_DELTA = 32449;
end;

else if NETTOOMSAETNING_1_DELTA >=20 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_NETTOOMSAETNING_1_DELTA = 32450;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_NETTOOMSAETNING_1_DELTA = 32450;
end;
end;
else if MISSING(NETTOOMSAETNING_1_DELTA) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_NETTOOMSAETNING_1_DELTA = 32450;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_NETTOOMSAETNING_1_DELTA = 32450;
end;


*------------------------------------------------------------*;
* Variable: KORTGAELDSSEVICERING_1;
*------------------------------------------------------------*;
if  NOT MISSING(KORTGAELDSSEVICERING_1) then do;
if KORTGAELDSSEVICERING_1 <-350 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_KORTGAELDSSEVICERING_1 = 32421;
end;

else if KORTGAELDSSEVICERING_1>=-350 and KORTGAELDSSEVICERING_1<0 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 6 ;
GRP_KORTGAELDSSEVICERING_1 = 32422;
end;

else if KORTGAELDSSEVICERING_1>=0 and KORTGAELDSSEVICERING_1<=0 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 24 ;
GRP_KORTGAELDSSEVICERING_1 = 32423;
end;

else if KORTGAELDSSEVICERING_1>0 and KORTGAELDSSEVICERING_1<25 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 104 ;
GRP_KORTGAELDSSEVICERING_1 = 32424;
end;

else if KORTGAELDSSEVICERING_1>=25 and KORTGAELDSSEVICERING_1<50 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 68 ;
GRP_KORTGAELDSSEVICERING_1 = 32425;
end;

else if KORTGAELDSSEVICERING_1>=50 and KORTGAELDSSEVICERING_1<90 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 39 ;
GRP_KORTGAELDSSEVICERING_1 = 32426;
end;

else if KORTGAELDSSEVICERING_1>=90 and KORTGAELDSSEVICERING_1<200 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 35 ;
GRP_KORTGAELDSSEVICERING_1 = 32427;
end;

else if KORTGAELDSSEVICERING_1>=200 and KORTGAELDSSEVICERING_1<300 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 26 ;
GRP_KORTGAELDSSEVICERING_1 = 32428;
end;

else if KORTGAELDSSEVICERING_1 >=300 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 5 ;
GRP_KORTGAELDSSEVICERING_1 = 32429;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_KORTGAELDSSEVICERING_1 = 32421;
end;
end;
else if MISSING(KORTGAELDSSEVICERING_1) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_KORTGAELDSSEVICERING_1 = 32421;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_KORTGAELDSSEVICERING_1 = 32421;
end;


*------------------------------------------------------------*;
* Variable: RENTEDAEKNINGSGRAD_1;
*------------------------------------------------------------*;
if  NOT MISSING(RENTEDAEKNINGSGRAD_1) then do;
if RENTEDAEKNINGSGRAD_1>=0 and RENTEDAEKNINGSGRAD_1<=0 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_RENTEDAEKNINGSGRAD_1 = 32451;
end;

else if RENTEDAEKNINGSGRAD_1>0 and RENTEDAEKNINGSGRAD_1<100 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 15 ;
GRP_RENTEDAEKNINGSGRAD_1 = 32452;
end;

else if RENTEDAEKNINGSGRAD_1>=100 and RENTEDAEKNINGSGRAD_1<300 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 22 ;
GRP_RENTEDAEKNINGSGRAD_1 = 32453;
end;

else if RENTEDAEKNINGSGRAD_1>=300 and RENTEDAEKNINGSGRAD_1<500 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 24 ;
GRP_RENTEDAEKNINGSGRAD_1 = 32454;
end;

else if RENTEDAEKNINGSGRAD_1>=500 and RENTEDAEKNINGSGRAD_1<1200 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 37 ;
GRP_RENTEDAEKNINGSGRAD_1 = 32455;
end;

else if RENTEDAEKNINGSGRAD_1>=1200 and RENTEDAEKNINGSGRAD_1<2300 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 50 ;
GRP_RENTEDAEKNINGSGRAD_1 = 32456;
end;

else if RENTEDAEKNINGSGRAD_1 >=2300 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 67 ;
GRP_RENTEDAEKNINGSGRAD_1 = 32457;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_RENTEDAEKNINGSGRAD_1 = 32451;
end;
end;
else if MISSING(RENTEDAEKNINGSGRAD_1) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_RENTEDAEKNINGSGRAD_1 = 32451;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_RENTEDAEKNINGSGRAD_1 = 32451;
end;


*------------------------------------------------------------*;
* Variable: GAELDSGRAD_1_DELTA;
*------------------------------------------------------------*;
if  NOT MISSING(GAELDSGRAD_1_DELTA) then do;
if GAELDSGRAD_1_DELTA <-10 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 32 ;
GRP_GAELDSGRAD_1_DELTA = 32442;
end;

else if GAELDSGRAD_1_DELTA>=-10 and GAELDSGRAD_1_DELTA<0 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 27 ;
GRP_GAELDSGRAD_1_DELTA = 32443;
end;

else if GAELDSGRAD_1_DELTA>=0 and GAELDSGRAD_1_DELTA<5 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 14 ;
GRP_GAELDSGRAD_1_DELTA = 32444;
end;

else if GAELDSGRAD_1_DELTA >=5 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_GAELDSGRAD_1_DELTA = 32445;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_GAELDSGRAD_1_DELTA = 32445;
end;
end;
else if MISSING(GAELDSGRAD_1_DELTA) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_GAELDSGRAD_1_DELTA = 32445;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_GAELDSGRAD_1_DELTA = 32445;
end;

SCORECARD_POINTS = EM_SCORECARD_POINTS;
run;
