data &m_output_table_nm;
set &m_scoring_abt_table_nm;

*------------------------------------------------------------*;
* DABT JUDGEMENTAL SCORE CODE;
*------------------------------------------------------------*;

EM_SCORECARD_POINTS = 0;

*------------------------------------------------------------*;
* Variable: TRANS_BALANCE_SUM;
*------------------------------------------------------------*;
if  NOT MISSING(TRANS_BALANCE_SUM) then do;
if TRANS_BALANCE_SUM <2147.07 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_TRANS_BALANCE_SUM = 32484;
end;

else if TRANS_BALANCE_SUM>=2147.07 and TRANS_BALANCE_SUM<12543.99 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 15 ;
GRP_TRANS_BALANCE_SUM = 32485;
end;

else if TRANS_BALANCE_SUM>=12543.99 and TRANS_BALANCE_SUM<22328 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 27 ;
GRP_TRANS_BALANCE_SUM = 32486;
end;

else if TRANS_BALANCE_SUM >=22328 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 40 ;
GRP_TRANS_BALANCE_SUM = 32487;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 12 ;
GRP_TRANS_BALANCE_SUM = 32488;
end;
end;
else if MISSING(TRANS_BALANCE_SUM) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 12 ;
GRP_TRANS_BALANCE_SUM = 32488;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 12 ;
GRP_TRANS_BALANCE_SUM = 32488;
end;


*------------------------------------------------------------*;
* Variable: DANKORT_ANTAL;
*------------------------------------------------------------*;
if  NOT MISSING(DANKORT_ANTAL) then do;
if DANKORT_ANTAL <1 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 380 ;
GRP_DANKORT_ANTAL = 32458;
end;

else if DANKORT_ANTAL>=1 and DANKORT_ANTAL<2 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 432 ;
GRP_DANKORT_ANTAL = 32459;
end;

else if DANKORT_ANTAL >=2 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 435 ;
GRP_DANKORT_ANTAL = 32460;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 398 ;
GRP_DANKORT_ANTAL = 32461;
end;
end;
else if MISSING(DANKORT_ANTAL) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 398 ;
GRP_DANKORT_ANTAL = 32461;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 398 ;
GRP_DANKORT_ANTAL = 32461;
end;


*------------------------------------------------------------*;
* Variable: KREOMS_VS_DEBOMS_MEAN_12MND;
*------------------------------------------------------------*;
if  NOT MISSING(KREOMS_VS_DEBOMS_MEAN_12MND) then do;
if KREOMS_VS_DEBOMS_MEAN_12MND <0.62 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 59 ;
GRP_KREOMS_VS_DEBOMS_MEAN_12MND = 32462;
end;

else if KREOMS_VS_DEBOMS_MEAN_12MND>=0.62 and KREOMS_VS_DEBOMS_MEAN_12MND<0.98 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 85 ;
GRP_KREOMS_VS_DEBOMS_MEAN_12MND = 32463;
end;

else if KREOMS_VS_DEBOMS_MEAN_12MND>=0.98 and KREOMS_VS_DEBOMS_MEAN_12MND<1.02 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 98 ;
GRP_KREOMS_VS_DEBOMS_MEAN_12MND = 32464;
end;

else if KREOMS_VS_DEBOMS_MEAN_12MND >=1.02 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 106 ;
GRP_KREOMS_VS_DEBOMS_MEAN_12MND = 32465;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_KREOMS_VS_DEBOMS_MEAN_12MND = 32466;
end;
end;
else if MISSING(KREOMS_VS_DEBOMS_MEAN_12MND) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_KREOMS_VS_DEBOMS_MEAN_12MND = 32466;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_KREOMS_VS_DEBOMS_MEAN_12MND = 32466;
end;


*------------------------------------------------------------*;
* Variable: UDNYTGRAD_KREDIT_MEAN_3MND;
*------------------------------------------------------------*;
if  NOT MISSING(UDNYTGRAD_KREDIT_MEAN_3MND) then do;
if UDNYTGRAD_KREDIT_MEAN_3MND <17.1 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 47 ;
GRP_UDNYTGRAD_KREDIT_MEAN_3MND = 32494;
end;

else if UDNYTGRAD_KREDIT_MEAN_3MND>=17.1 and UDNYTGRAD_KREDIT_MEAN_3MND<85.18 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 31 ;
GRP_UDNYTGRAD_KREDIT_MEAN_3MND = 32495;
end;

else if UDNYTGRAD_KREDIT_MEAN_3MND>=85.18 and UDNYTGRAD_KREDIT_MEAN_3MND<100 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 15 ;
GRP_UDNYTGRAD_KREDIT_MEAN_3MND = 32496;
end;

else if UDNYTGRAD_KREDIT_MEAN_3MND >=100 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_UDNYTGRAD_KREDIT_MEAN_3MND = 32497;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 29 ;
GRP_UDNYTGRAD_KREDIT_MEAN_3MND = 32498;
end;
end;
else if MISSING(UDNYTGRAD_KREDIT_MEAN_3MND) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 29 ;
GRP_UDNYTGRAD_KREDIT_MEAN_3MND = 32498;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 29 ;
GRP_UDNYTGRAD_KREDIT_MEAN_3MND = 32498;
end;


*------------------------------------------------------------*;
* Variable: OVERTRAEK_SUM_MEAN_12MND;
*------------------------------------------------------------*;
if  NOT MISSING(OVERTRAEK_SUM_MEAN_12MND) then do;
if OVERTRAEK_SUM_MEAN_12MND <2.57 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 223 ;
GRP_OVERTRAEK_SUM_MEAN_12MND = 32471;
end;

else if OVERTRAEK_SUM_MEAN_12MND>=2.57 and OVERTRAEK_SUM_MEAN_12MND<261.33 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 163 ;
GRP_OVERTRAEK_SUM_MEAN_12MND = 32472;
end;

else if OVERTRAEK_SUM_MEAN_12MND>=261.33 and OVERTRAEK_SUM_MEAN_12MND<1098.35 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 114 ;
GRP_OVERTRAEK_SUM_MEAN_12MND = 32473;
end;

else if OVERTRAEK_SUM_MEAN_12MND>=1098.35 and OVERTRAEK_SUM_MEAN_12MND<5807.61 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 62 ;
GRP_OVERTRAEK_SUM_MEAN_12MND = 32474;
end;

else if OVERTRAEK_SUM_MEAN_12MND >=5807.61 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_OVERTRAEK_SUM_MEAN_12MND = 32475;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 223 ;
GRP_OVERTRAEK_SUM_MEAN_12MND = 32471;
end;
end;
else if MISSING(OVERTRAEK_SUM_MEAN_12MND) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 223 ;
GRP_OVERTRAEK_SUM_MEAN_12MND = 32471;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 223 ;
GRP_OVERTRAEK_SUM_MEAN_12MND = 32471;
end;


*------------------------------------------------------------*;
* Variable: OVERTRK_MAX_AKT_1;
*------------------------------------------------------------*;
if  NOT MISSING(OVERTRK_MAX_AKT_1) then do;
if OVERTRK_MAX_AKT_1 <31 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 127 ;
GRP_OVERTRK_MAX_AKT_1 = 32476;
end;

else if OVERTRK_MAX_AKT_1>=31 and OVERTRK_MAX_AKT_1<40 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 51 ;
GRP_OVERTRK_MAX_AKT_1 = 32477;
end;

else if OVERTRK_MAX_AKT_1 >=40 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_OVERTRK_MAX_AKT_1 = 32478;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 127 ;
GRP_OVERTRK_MAX_AKT_1 = 32476;
end;
end;
else if MISSING(OVERTRK_MAX_AKT_1) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 127 ;
GRP_OVERTRK_MAX_AKT_1 = 32476;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 127 ;
GRP_OVERTRK_MAX_AKT_1 = 32476;
end;


*------------------------------------------------------------*;
* Variable: NEM_KTO_ANT;
*------------------------------------------------------------*;
if  NOT MISSING(NEM_KTO_ANT) then do;
if NEM_KTO_ANT <1 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_NEM_KTO_ANT = 32467;
end;

else if NEM_KTO_ANT>=1 and NEM_KTO_ANT<2 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 16 ;
GRP_NEM_KTO_ANT = 32468;
end;

else if NEM_KTO_ANT >=2 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 25 ;
GRP_NEM_KTO_ANT = 32469;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 3 ;
GRP_NEM_KTO_ANT = 32470;
end;
end;
else if MISSING(NEM_KTO_ANT) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 3 ;
GRP_NEM_KTO_ANT = 32470;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 3 ;
GRP_NEM_KTO_ANT = 32470;
end;


*------------------------------------------------------------*;
* Variable: PRIVAT_SOLIDITET;
*------------------------------------------------------------*;
if  NOT MISSING(PRIVAT_SOLIDITET) then do;
if PRIVAT_SOLIDITET <-187.22 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_PRIVAT_SOLIDITET = 32479;
end;

else if PRIVAT_SOLIDITET>=-187.22 and PRIVAT_SOLIDITET<-18.1600 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 14 ;
GRP_PRIVAT_SOLIDITET = 32480;
end;

else if PRIVAT_SOLIDITET>=-18.1600 and PRIVAT_SOLIDITET<-6.36 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 28 ;
GRP_PRIVAT_SOLIDITET = 32481;
end;

else if PRIVAT_SOLIDITET >=-6.36 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 47 ;
GRP_PRIVAT_SOLIDITET = 32482;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 12 ;
GRP_PRIVAT_SOLIDITET = 32483;
end;
end;
else if MISSING(PRIVAT_SOLIDITET) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 12 ;
GRP_PRIVAT_SOLIDITET = 32483;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 12 ;
GRP_PRIVAT_SOLIDITET = 32483;
end;


*------------------------------------------------------------*;
* Variable: UDLAAN_VS_KREDITOMS;
*------------------------------------------------------------*;
if  NOT MISSING(UDLAAN_VS_KREDITOMS) then do;
if UDLAAN_VS_KREDITOMS <4.6 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 79 ;
GRP_UDLAAN_VS_KREDITOMS = 32489;
end;

else if UDLAAN_VS_KREDITOMS>=4.6 and UDLAAN_VS_KREDITOMS<10.39 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 67 ;
GRP_UDLAAN_VS_KREDITOMS = 32490;
end;

else if UDLAAN_VS_KREDITOMS>=10.39 and UDLAAN_VS_KREDITOMS<60.14 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 53 ;
GRP_UDLAAN_VS_KREDITOMS = 32491;
end;

else if UDLAAN_VS_KREDITOMS >=60.14 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 32 ;
GRP_UDLAAN_VS_KREDITOMS = 32492;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_UDLAAN_VS_KREDITOMS = 32493;
end;
end;
else if MISSING(UDLAAN_VS_KREDITOMS) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_UDLAAN_VS_KREDITOMS = 32493;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_UDLAAN_VS_KREDITOMS = 32493;
end;

SCORECARD_POINTS = EM_SCORECARD_POINTS;
run;
