data &m_output_table_nm;
set &m_scoring_abt_table_nm;

*------------------------------------------------------------*;
* DABT JUDGEMENTAL SCORE CODE;
*------------------------------------------------------------*;

EM_SCORECARD_POINTS = 0;

*------------------------------------------------------------*;
* Variable: DEPOT_FRIEMIDL_SUM_MEAN_6MND;
*------------------------------------------------------------*;
if  NOT MISSING(DEPOT_FRIEMIDL_SUM_MEAN_6MND) then do;
if DEPOT_FRIEMIDL_SUM_MEAN_6MND <=0 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 443659 ;
GRP_DEPOT_FRIEMIDL_SUM_MEAN_6MND = 22897;
end;

else if DEPOT_FRIEMIDL_SUM_MEAN_6MND>0 and DEPOT_FRIEMIDL_SUM_MEAN_6MND<=100000 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -3549269 ;
GRP_DEPOT_FRIEMIDL_SUM_MEAN_6MND = 22898;
end;

else if DEPOT_FRIEMIDL_SUM_MEAN_6MND>100000 and DEPOT_FRIEMIDL_SUM_MEAN_6MND<=500000 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -7542197 ;
GRP_DEPOT_FRIEMIDL_SUM_MEAN_6MND = 22899;
end;

else if DEPOT_FRIEMIDL_SUM_MEAN_6MND >500000 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -15528052 ;
GRP_DEPOT_FRIEMIDL_SUM_MEAN_6MND = 22900;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 443659 ;
GRP_DEPOT_FRIEMIDL_SUM_MEAN_6MND = 22897;
end;
end;
else if MISSING(DEPOT_FRIEMIDL_SUM_MEAN_6MND) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 443659 ;
GRP_DEPOT_FRIEMIDL_SUM_MEAN_6MND = 22897;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 443659 ;
GRP_DEPOT_FRIEMIDL_SUM_MEAN_6MND = 22897;
end;


*------------------------------------------------------------*;
* Variable: INDLAAN_SUM_MEAN_6MND;
*------------------------------------------------------------*;
if  NOT MISSING(INDLAAN_SUM_MEAN_6MND) then do;
if INDLAAN_SUM_MEAN_6MND <50000 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 13000425 ;
GRP_INDLAAN_SUM_MEAN_6MND = 22901;
end;

else if INDLAAN_SUM_MEAN_6MND>=50000 and INDLAAN_SUM_MEAN_6MND<250000 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 6158096 ;
GRP_INDLAAN_SUM_MEAN_6MND = 22902;
end;

else if INDLAAN_SUM_MEAN_6MND>=250000 and INDLAAN_SUM_MEAN_6MND<750000 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -684233 ;
GRP_INDLAAN_SUM_MEAN_6MND = 22903;
end;

else if INDLAAN_SUM_MEAN_6MND >=750000 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -14368891 ;
GRP_INDLAAN_SUM_MEAN_6MND = 22904;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 13000425 ;
GRP_INDLAAN_SUM_MEAN_6MND = 22901;
end;
end;
else if MISSING(INDLAAN_SUM_MEAN_6MND) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 13000425 ;
GRP_INDLAAN_SUM_MEAN_6MND = 22901;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 13000425 ;
GRP_INDLAAN_SUM_MEAN_6MND = 22901;
end;


*------------------------------------------------------------*;
* Variable: OVERTRK_MAX_AKT_MAX_6MND;
*------------------------------------------------------------*;
if  NOT MISSING(OVERTRK_MAX_AKT_MAX_6MND) then do;
if OVERTRK_MAX_AKT_MAX_6MND<30 and OVERTRK_MAX_AKT_MAX_6MND<30 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -1140688 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 22905;
end;

else if OVERTRK_MAX_AKT_MAX_6MND>=30 and OVERTRK_MAX_AKT_MAX_6MND<60 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 15969635 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 22906;
end;

else if OVERTRK_MAX_AKT_MAX_6MND>=60 and OVERTRK_MAX_AKT_MAX_6MND<90 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 33079958 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 22907;
end;

else if OVERTRK_MAX_AKT_MAX_6MND>=90 and OVERTRK_MAX_AKT_MAX_6MND then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 50190281 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 22908;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -1140688 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 22905;
end;
end;
else if MISSING(OVERTRK_MAX_AKT_MAX_6MND) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -1140688 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 22905;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -1140688 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 22905;
end;

SCORECARD_POINTS = EM_SCORECARD_POINTS;
run;
