data &m_output_table_nm;
set &m_scoring_abt_table_nm;

*------------------------------------------------------------*;
* DABT JUDGEMENTAL SCORE CODE;
*------------------------------------------------------------*;

EM_SCORECARD_POINTS = 0;

*------------------------------------------------------------*;
* Variable: RYKKER_123_HIST;
*------------------------------------------------------------*;
if  NOT MISSING(RYKKER_123_HIST) then do;
if RYKKER_123_HIST <=0.5 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -221165 ;
GRP_RYKKER_123_HIST = 21776;
end;

else if RYKKER_123_HIST >0.5 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 4521335 ;
GRP_RYKKER_123_HIST = 21777;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -221165 ;
GRP_RYKKER_123_HIST = 21776;
end;
end;
else if MISSING(RYKKER_123_HIST) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -221165 ;
GRP_RYKKER_123_HIST = 21776;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -221165 ;
GRP_RYKKER_123_HIST = 21776;
end;


*------------------------------------------------------------*;
* Variable: FORMUE_NETTO;
*------------------------------------------------------------*;
if  NOT MISSING(FORMUE_NETTO) then do;
if FORMUE_NETTO <-500000 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 21527531 ;
GRP_FORMUE_NETTO = 21751;
end;

else if FORMUE_NETTO>=-500000 and FORMUE_NETTO<-100000 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 13992491 ;
GRP_FORMUE_NETTO = 21752;
end;

else if FORMUE_NETTO>=-100000 and FORMUE_NETTO<50000 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 6457450 ;
GRP_FORMUE_NETTO = 21753;
end;

else if FORMUE_NETTO>=50000 and FORMUE_NETTO<250000 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -1077590 ;
GRP_FORMUE_NETTO = 21754;
end;

else if FORMUE_NETTO>=250000 and FORMUE_NETTO<500000 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -8612631 ;
GRP_FORMUE_NETTO = 21755;
end;

else if FORMUE_NETTO>=500000 and FORMUE_NETTO<1000000 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -16147671 ;
GRP_FORMUE_NETTO = 21756;
end;

else if FORMUE_NETTO>=1000000 and FORMUE_NETTO<2500000 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -23682713 ;
GRP_FORMUE_NETTO = 21757;
end;

else if FORMUE_NETTO >=2500000 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -31217753 ;
GRP_FORMUE_NETTO = 21758;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 13992491 ;
GRP_FORMUE_NETTO = 21752;
end;
end;
else if MISSING(FORMUE_NETTO) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 13992491 ;
GRP_FORMUE_NETTO = 21752;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 13992491 ;
GRP_FORMUE_NETTO = 21752;
end;


*------------------------------------------------------------*;
* Variable: AFVIKLING_UDLAAN;
*------------------------------------------------------------*;
if  NOT MISSING(AFVIKLING_UDLAAN) then do;
if AFVIKLING_UDLAAN in (1) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -4220290 ;
GRP_AFVIKLING_UDLAAN = 21732;
end;

else if AFVIKLING_UDLAAN in (2) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 1480884 ;
GRP_AFVIKLING_UDLAAN = 21733;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 1480884 ;
GRP_AFVIKLING_UDLAAN = 21733;
end;
end;
else if MISSING(AFVIKLING_UDLAAN) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 1480884 ;
GRP_AFVIKLING_UDLAAN = 21733;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 1480884 ;
GRP_AFVIKLING_UDLAAN = 21733;
end;


*------------------------------------------------------------*;
* Variable: OVERTRK_MAX_AKT_MAX_6MND;
*------------------------------------------------------------*;
if  NOT MISSING(OVERTRK_MAX_AKT_MAX_6MND) then do;
if OVERTRK_MAX_AKT_MAX_6MND <30 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -2120473 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 21759;
end;

else if OVERTRK_MAX_AKT_MAX_6MND>=30 and OVERTRK_MAX_AKT_MAX_6MND<60 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 15147275 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 21760;
end;

else if OVERTRK_MAX_AKT_MAX_6MND>=60 and OVERTRK_MAX_AKT_MAX_6MND<90 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 32415023 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 21761;
end;

else if OVERTRK_MAX_AKT_MAX_6MND >=90 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 49682771 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 21762;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -2120473 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 21759;
end;
end;
else if MISSING(OVERTRK_MAX_AKT_MAX_6MND) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -2120473 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 21759;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -2120473 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 21759;
end;


*------------------------------------------------------------*;
* Variable: RAAD_OPFYLD_SOLIDITET;
*------------------------------------------------------------*;
if  NOT MISSING(RAAD_OPFYLD_SOLIDITET) then do;
if RAAD_OPFYLD_SOLIDITET in (1) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 27498450 ;
GRP_RAAD_OPFYLD_SOLIDITET = 21769;
end;

else if RAAD_OPFYLD_SOLIDITET in (2) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 18866702 ;
GRP_RAAD_OPFYLD_SOLIDITET = 21770;
end;

else if RAAD_OPFYLD_SOLIDITET in (3) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 10234953 ;
GRP_RAAD_OPFYLD_SOLIDITET = 21771;
end;

else if RAAD_OPFYLD_SOLIDITET in (4) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 1603205 ;
GRP_RAAD_OPFYLD_SOLIDITET = 21772;
end;

else if RAAD_OPFYLD_SOLIDITET in (5) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 10234953 ;
GRP_RAAD_OPFYLD_SOLIDITET = 21771;
end;

else if RAAD_OPFYLD_SOLIDITET in (6) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 1603205 ;
GRP_RAAD_OPFYLD_SOLIDITET = 21772;
end;

else if RAAD_OPFYLD_SOLIDITET in (7) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -7028544 ;
GRP_RAAD_OPFYLD_SOLIDITET = 21773;
end;

else if RAAD_OPFYLD_SOLIDITET in (8) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -7028544 ;
GRP_RAAD_OPFYLD_SOLIDITET = 21773;
end;

else if RAAD_OPFYLD_SOLIDITET in (9) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -15660293 ;
GRP_RAAD_OPFYLD_SOLIDITET = 21774;
end;

else if RAAD_OPFYLD_SOLIDITET in (10) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -7028544 ;
GRP_RAAD_OPFYLD_SOLIDITET = 21773;
end;

else if RAAD_OPFYLD_SOLIDITET in (11) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -24292041 ;
GRP_RAAD_OPFYLD_SOLIDITET = 21775;
end;

else if RAAD_OPFYLD_SOLIDITET in (12) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 18866702 ;
GRP_RAAD_OPFYLD_SOLIDITET = 21770;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 18866702 ;
GRP_RAAD_OPFYLD_SOLIDITET = 21770;
end;
end;
else if MISSING(RAAD_OPFYLD_SOLIDITET) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 18866702 ;
GRP_RAAD_OPFYLD_SOLIDITET = 21770;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 18866702 ;
GRP_RAAD_OPFYLD_SOLIDITET = 21770;
end;


*------------------------------------------------------------*;
* Variable: DEPOT_FRIEMIDL_SUM_MEAN_6MND;
*------------------------------------------------------------*;
if  NOT MISSING(DEPOT_FRIEMIDL_SUM_MEAN_6MND) then do;
if DEPOT_FRIEMIDL_SUM_MEAN_6MND <=10000 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 544283 ;
GRP_DEPOT_FRIEMIDL_SUM_MEAN_6MND = 21747;
end;

else if DEPOT_FRIEMIDL_SUM_MEAN_6MND>10000 and DEPOT_FRIEMIDL_SUM_MEAN_6MND<=50000 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -5628909 ;
GRP_DEPOT_FRIEMIDL_SUM_MEAN_6MND = 21748;
end;

else if DEPOT_FRIEMIDL_SUM_MEAN_6MND>50000 and DEPOT_FRIEMIDL_SUM_MEAN_6MND<=250000 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -11802101 ;
GRP_DEPOT_FRIEMIDL_SUM_MEAN_6MND = 21749;
end;

else if DEPOT_FRIEMIDL_SUM_MEAN_6MND >250000 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -17975292 ;
GRP_DEPOT_FRIEMIDL_SUM_MEAN_6MND = 21750;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 544283 ;
GRP_DEPOT_FRIEMIDL_SUM_MEAN_6MND = 21747;
end;
end;
else if MISSING(DEPOT_FRIEMIDL_SUM_MEAN_6MND) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 544283 ;
GRP_DEPOT_FRIEMIDL_SUM_MEAN_6MND = 21747;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 544283 ;
GRP_DEPOT_FRIEMIDL_SUM_MEAN_6MND = 21747;
end;


*------------------------------------------------------------*;
* Variable: INDLAAN_SUM_MEAN_6MND;
*------------------------------------------------------------*;
if  NOT MISSING(INDLAAN_SUM_MEAN_6MND) then do;
if INDLAAN_SUM_MEAN_6MND <10000 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 6691209 ;
GRP_INDLAAN_SUM_MEAN_6MND = 21763;
end;

else if INDLAAN_SUM_MEAN_6MND>=10000 and INDLAAN_SUM_MEAN_6MND<50000 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 1714222 ;
GRP_INDLAAN_SUM_MEAN_6MND = 21764;
end;

else if INDLAAN_SUM_MEAN_6MND>=50000 and INDLAAN_SUM_MEAN_6MND<100000 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -3262766 ;
GRP_INDLAAN_SUM_MEAN_6MND = 21765;
end;

else if INDLAAN_SUM_MEAN_6MND>=100000 and INDLAAN_SUM_MEAN_6MND<250000 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -8239754 ;
GRP_INDLAAN_SUM_MEAN_6MND = 21766;
end;

else if INDLAAN_SUM_MEAN_6MND >=250000 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -13216741 ;
GRP_INDLAAN_SUM_MEAN_6MND = 21767;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_INDLAAN_SUM_MEAN_6MND = 21768;
end;
end;
else if MISSING(INDLAAN_SUM_MEAN_6MND) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_INDLAAN_SUM_MEAN_6MND = 21768;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_INDLAAN_SUM_MEAN_6MND = 21768;
end;


*------------------------------------------------------------*;
* Variable: ALDER;
*------------------------------------------------------------*;
if  NOT MISSING(ALDER) then do;
if ALDER <30 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -12641601 ;
GRP_ALDER = 21734;
end;

else if ALDER>=30 and ALDER<45 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -4281305 ;
GRP_ALDER = 21735;
end;

else if ALDER>=45 and ALDER<55 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 4078991 ;
GRP_ALDER = 21736;
end;

else if ALDER>=55 and ALDER<65 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 8259139 ;
GRP_ALDER = 21737;
end;

else if ALDER>=65 and ALDER<75 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 12439287 ;
GRP_ALDER = 21738;
end;

else if ALDER >=75 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 16619435 ;
GRP_ALDER = 21739;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 8259139 ;
GRP_ALDER = 21737;
end;
end;
else if MISSING(ALDER) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 8259139 ;
GRP_ALDER = 21737;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 8259139 ;
GRP_ALDER = 21737;
end;


*------------------------------------------------------------*;
* Variable: ALDER_BOLIGFORM_GEARING;
*------------------------------------------------------------*;
if  NOT MISSING(ALDER_BOLIGFORM_GEARING) then do;
if ALDER_BOLIGFORM_GEARING in (1) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -29948825 ;
GRP_ALDER_BOLIGFORM_GEARING = 21740;
end;

else if ALDER_BOLIGFORM_GEARING in (2) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -4291196 ;
GRP_ALDER_BOLIGFORM_GEARING = 21741;
end;

else if ALDER_BOLIGFORM_GEARING in (3) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 12813891 ;
GRP_ALDER_BOLIGFORM_GEARING = 21742;
end;

else if ALDER_BOLIGFORM_GEARING in (4) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 21366434 ;
GRP_ALDER_BOLIGFORM_GEARING = 21743;
end;

else if ALDER_BOLIGFORM_GEARING in (5) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -38501367 ;
GRP_ALDER_BOLIGFORM_GEARING = 21744;
end;

else if ALDER_BOLIGFORM_GEARING in (6) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -4291196 ;
GRP_ALDER_BOLIGFORM_GEARING = 21741;
end;

else if ALDER_BOLIGFORM_GEARING in (7) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 12813891 ;
GRP_ALDER_BOLIGFORM_GEARING = 21742;
end;

else if ALDER_BOLIGFORM_GEARING in (8) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 21366434 ;
GRP_ALDER_BOLIGFORM_GEARING = 21743;
end;

else if ALDER_BOLIGFORM_GEARING in (9) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -21396281 ;
GRP_ALDER_BOLIGFORM_GEARING = 21745;
end;

else if ALDER_BOLIGFORM_GEARING in (10) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 4261347 ;
GRP_ALDER_BOLIGFORM_GEARING = 21746;
end;

else if ALDER_BOLIGFORM_GEARING in (11) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 12813891 ;
GRP_ALDER_BOLIGFORM_GEARING = 21742;
end;

else if ALDER_BOLIGFORM_GEARING in (12) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 21366434 ;
GRP_ALDER_BOLIGFORM_GEARING = 21743;
end;

else if ALDER_BOLIGFORM_GEARING in (13) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -38501367 ;
GRP_ALDER_BOLIGFORM_GEARING = 21744;
end;

else if ALDER_BOLIGFORM_GEARING in (14) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -4291196 ;
GRP_ALDER_BOLIGFORM_GEARING = 21741;
end;

else if ALDER_BOLIGFORM_GEARING in (15) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 12813891 ;
GRP_ALDER_BOLIGFORM_GEARING = 21742;
end;

else if ALDER_BOLIGFORM_GEARING in (16) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 21366434 ;
GRP_ALDER_BOLIGFORM_GEARING = 21743;
end;

else if ALDER_BOLIGFORM_GEARING in (17) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -21396281 ;
GRP_ALDER_BOLIGFORM_GEARING = 21745;
end;

else if ALDER_BOLIGFORM_GEARING in (18) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 4261347 ;
GRP_ALDER_BOLIGFORM_GEARING = 21746;
end;

else if ALDER_BOLIGFORM_GEARING in (19) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 12813891 ;
GRP_ALDER_BOLIGFORM_GEARING = 21742;
end;

else if ALDER_BOLIGFORM_GEARING in (20) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 21366434 ;
GRP_ALDER_BOLIGFORM_GEARING = 21743;
end;

else if ALDER_BOLIGFORM_GEARING in (21) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -38501367 ;
GRP_ALDER_BOLIGFORM_GEARING = 21744;
end;

else if ALDER_BOLIGFORM_GEARING in (22) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -4291196 ;
GRP_ALDER_BOLIGFORM_GEARING = 21741;
end;

else if ALDER_BOLIGFORM_GEARING in (23) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 12813891 ;
GRP_ALDER_BOLIGFORM_GEARING = 21742;
end;

else if ALDER_BOLIGFORM_GEARING in (24) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 21366434 ;
GRP_ALDER_BOLIGFORM_GEARING = 21743;
end;

else if ALDER_BOLIGFORM_GEARING in (25) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 21366434 ;
GRP_ALDER_BOLIGFORM_GEARING = 21743;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 21366434 ;
GRP_ALDER_BOLIGFORM_GEARING = 21743;
end;
end;
else if MISSING(ALDER_BOLIGFORM_GEARING) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 21366434 ;
GRP_ALDER_BOLIGFORM_GEARING = 21743;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 21366434 ;
GRP_ALDER_BOLIGFORM_GEARING = 21743;
end;


*------------------------------------------------------------*;
* Variable: AFDF_REST_L_OG_RAADIGOPFY;
*------------------------------------------------------------*;
if  NOT MISSING(AFDF_REST_L_OG_RAADIGOPFY) then do;
if AFDF_REST_L_OG_RAADIGOPFY in (1) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 12080372 ;
GRP_AFDF_REST_L_OG_RAADIGOPFY = 21728;
end;

else if AFDF_REST_L_OG_RAADIGOPFY in (2) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 4645753 ;
GRP_AFDF_REST_L_OG_RAADIGOPFY = 21729;
end;

else if AFDF_REST_L_OG_RAADIGOPFY in (3) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 928444 ;
GRP_AFDF_REST_L_OG_RAADIGOPFY = 21730;
end;

else if AFDF_REST_L_OG_RAADIGOPFY in (4) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -2788866 ;
GRP_AFDF_REST_L_OG_RAADIGOPFY = 21731;
end;

else if AFDF_REST_L_OG_RAADIGOPFY in (5) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -2788866 ;
GRP_AFDF_REST_L_OG_RAADIGOPFY = 21731;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -2788866 ;
GRP_AFDF_REST_L_OG_RAADIGOPFY = 21731;
end;
end;
else if MISSING(AFDF_REST_L_OG_RAADIGOPFY) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -2788866 ;
GRP_AFDF_REST_L_OG_RAADIGOPFY = 21731;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + -2788866 ;
GRP_AFDF_REST_L_OG_RAADIGOPFY = 21731;
end;

SCORECARD_POINTS = EM_SCORECARD_POINTS;
run;
