data &m_output_table_nm;
set &m_scoring_abt_table_nm;

*------------------------------------------------------------*;
* DABT JUDGEMENTAL SCORE CODE;
*------------------------------------------------------------*;

EM_SCORECARD_POINTS = 0;

*------------------------------------------------------------*;
* Variable: UDNYTGRAD_KREDIT_MEAN_3MND;
*------------------------------------------------------------*;
if  NOT MISSING(UDNYTGRAD_KREDIT_MEAN_3MND) then do;
if UDNYTGRAD_KREDIT_MEAN_3MND <25 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 105 ;
GRP_UDNYTGRAD_KREDIT_MEAN_3MND = 29887;
end;

else if UDNYTGRAD_KREDIT_MEAN_3MND>=25 and UDNYTGRAD_KREDIT_MEAN_3MND<65 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 68 ;
GRP_UDNYTGRAD_KREDIT_MEAN_3MND = 29888;
end;

else if UDNYTGRAD_KREDIT_MEAN_3MND>=65 and UDNYTGRAD_KREDIT_MEAN_3MND<80 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 58 ;
GRP_UDNYTGRAD_KREDIT_MEAN_3MND = 29889;
end;

else if UDNYTGRAD_KREDIT_MEAN_3MND>=80 and UDNYTGRAD_KREDIT_MEAN_3MND<95 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 47 ;
GRP_UDNYTGRAD_KREDIT_MEAN_3MND = 29890;
end;

else if UDNYTGRAD_KREDIT_MEAN_3MND>=95 and UDNYTGRAD_KREDIT_MEAN_3MND<100 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 31 ;
GRP_UDNYTGRAD_KREDIT_MEAN_3MND = 29891;
end;

else if UDNYTGRAD_KREDIT_MEAN_3MND>=100 and UDNYTGRAD_KREDIT_MEAN_3MND<105 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 21 ;
GRP_UDNYTGRAD_KREDIT_MEAN_3MND = 29892;
end;

else if UDNYTGRAD_KREDIT_MEAN_3MND >=105 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_UDNYTGRAD_KREDIT_MEAN_3MND = 29893;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 105 ;
GRP_UDNYTGRAD_KREDIT_MEAN_3MND = 29887;
end;
end;
else if MISSING(UDNYTGRAD_KREDIT_MEAN_3MND) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 105 ;
GRP_UDNYTGRAD_KREDIT_MEAN_3MND = 29887;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 105 ;
GRP_UDNYTGRAD_KREDIT_MEAN_3MND = 29887;
end;


*------------------------------------------------------------*;
* Variable: AVG_DEBOMS_AVG_KREDOMS;
*------------------------------------------------------------*;
if  NOT MISSING(AVG_DEBOMS_AVG_KREDOMS) then do;
if AVG_DEBOMS_AVG_KREDOMS <100 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 603 ;
GRP_AVG_DEBOMS_AVG_KREDOMS = 29882;
end;

else if AVG_DEBOMS_AVG_KREDOMS>=100 and AVG_DEBOMS_AVG_KREDOMS<110 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 583 ;
GRP_AVG_DEBOMS_AVG_KREDOMS = 29883;
end;

else if AVG_DEBOMS_AVG_KREDOMS>=110 and AVG_DEBOMS_AVG_KREDOMS<155 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 576 ;
GRP_AVG_DEBOMS_AVG_KREDOMS = 29884;
end;

else if AVG_DEBOMS_AVG_KREDOMS>=155 and AVG_DEBOMS_AVG_KREDOMS<290 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 558 ;
GRP_AVG_DEBOMS_AVG_KREDOMS = 29885;
end;

else if AVG_DEBOMS_AVG_KREDOMS >=290 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 552 ;
GRP_AVG_DEBOMS_AVG_KREDOMS = 29886;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 552 ;
GRP_AVG_DEBOMS_AVG_KREDOMS = 29886;
end;
end;
else if MISSING(AVG_DEBOMS_AVG_KREDOMS) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 552 ;
GRP_AVG_DEBOMS_AVG_KREDOMS = 29886;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 552 ;
GRP_AVG_DEBOMS_AVG_KREDOMS = 29886;
end;


*------------------------------------------------------------*;
* Variable: MIN_KREDOMS_AVG_KREDOMS;
*------------------------------------------------------------*;
if  NOT MISSING(MIN_KREDOMS_AVG_KREDOMS) then do;
if MIN_KREDOMS_AVG_KREDOMS <10 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_MIN_KREDOMS_AVG_KREDOMS = 29894;
end;

else if MIN_KREDOMS_AVG_KREDOMS>=10 and MIN_KREDOMS_AVG_KREDOMS<45 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_MIN_KREDOMS_AVG_KREDOMS = 29894;
end;

else if MIN_KREDOMS_AVG_KREDOMS>=45 and MIN_KREDOMS_AVG_KREDOMS<60 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_MIN_KREDOMS_AVG_KREDOMS = 29894;
end;

else if MIN_KREDOMS_AVG_KREDOMS>=60 and MIN_KREDOMS_AVG_KREDOMS<75 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_MIN_KREDOMS_AVG_KREDOMS = 29894;
end;

else if MIN_KREDOMS_AVG_KREDOMS >=75 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_MIN_KREDOMS_AVG_KREDOMS = 29894;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_MIN_KREDOMS_AVG_KREDOMS = 29894;
end;
end;
else if MISSING(MIN_KREDOMS_AVG_KREDOMS) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_MIN_KREDOMS_AVG_KREDOMS = 29894;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_MIN_KREDOMS_AVG_KREDOMS = 29894;
end;


*------------------------------------------------------------*;
* Variable: UDLAAN_SUM_EBITDA;
*------------------------------------------------------------*;
if  NOT MISSING(UDLAAN_SUM_EBITDA) then do;
if UDLAAN_SUM_EBITDA <-2020 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_UDLAAN_SUM_EBITDA = 29912;
end;

else if UDLAAN_SUM_EBITDA>=-2020 and UDLAAN_SUM_EBITDA<-620 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 15 ;
GRP_UDLAAN_SUM_EBITDA = 29913;
end;

else if UDLAAN_SUM_EBITDA>=-620 and UDLAAN_SUM_EBITDA<-420 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 25 ;
GRP_UDLAAN_SUM_EBITDA = 29914;
end;

else if UDLAAN_SUM_EBITDA>=-420 and UDLAAN_SUM_EBITDA<-220 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 37 ;
GRP_UDLAAN_SUM_EBITDA = 29915;
end;

else if UDLAAN_SUM_EBITDA>=-220 and UDLAAN_SUM_EBITDA<-110 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 45 ;
GRP_UDLAAN_SUM_EBITDA = 29916;
end;

else if UDLAAN_SUM_EBITDA>=-110 and UDLAAN_SUM_EBITDA<-10 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 54 ;
GRP_UDLAAN_SUM_EBITDA = 29917;
end;

else if UDLAAN_SUM_EBITDA>=-10 and UDLAAN_SUM_EBITDA<0 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 123 ;
GRP_UDLAAN_SUM_EBITDA = 29918;
end;

else if UDLAAN_SUM_EBITDA>=0 and UDLAAN_SUM_EBITDA<=0 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 7 ;
GRP_UDLAAN_SUM_EBITDA = 29919;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 7 ;
GRP_UDLAAN_SUM_EBITDA = 29919;
end;
end;
else if MISSING(UDLAAN_SUM_EBITDA) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 7 ;
GRP_UDLAAN_SUM_EBITDA = 29919;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 7 ;
GRP_UDLAAN_SUM_EBITDA = 29919;
end;


*------------------------------------------------------------*;
* Variable: OVERTRK_MAX_AKT_MAX_6MND;
*------------------------------------------------------------*;
if  NOT MISSING(OVERTRK_MAX_AKT_MAX_6MND) then do;
if OVERTRK_MAX_AKT_MAX_6MND>=0 and OVERTRK_MAX_AKT_MAX_6MND<=0 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 122 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 29902;
end;

else if OVERTRK_MAX_AKT_MAX_6MND>0 and OVERTRK_MAX_AKT_MAX_6MND<=5 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 91 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 29903;
end;

else if OVERTRK_MAX_AKT_MAX_6MND>5 and OVERTRK_MAX_AKT_MAX_6MND<=20 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 69 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 29904;
end;

else if OVERTRK_MAX_AKT_MAX_6MND>20 and OVERTRK_MAX_AKT_MAX_6MND<=30 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 56 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 29905;
end;

else if OVERTRK_MAX_AKT_MAX_6MND>30 and OVERTRK_MAX_AKT_MAX_6MND<=60 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 39 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 29906;
end;

else if OVERTRK_MAX_AKT_MAX_6MND>60 and OVERTRK_MAX_AKT_MAX_6MND<=90 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 3 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 29907;
end;

else if OVERTRK_MAX_AKT_MAX_6MND>90 and OVERTRK_MAX_AKT_MAX_6MND then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 29908;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 122 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 29902;
end;
end;
else if MISSING(OVERTRK_MAX_AKT_MAX_6MND) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 122 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 29902;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 122 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 29902;
end;


*------------------------------------------------------------*;
* Variable: OVERTR_EGENKAP;
*------------------------------------------------------------*;
if  NOT MISSING(OVERTR_EGENKAP) then do;
if OVERTR_EGENKAP <0 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 7 ;
GRP_OVERTR_EGENKAP = 29895;
end;

else if OVERTR_EGENKAP>=0 and OVERTR_EGENKAP<=0 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 50 ;
GRP_OVERTR_EGENKAP = 29896;
end;

else if OVERTR_EGENKAP>0 and OVERTR_EGENKAP<.05 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 35 ;
GRP_OVERTR_EGENKAP = 29897;
end;

else if OVERTR_EGENKAP>=.05 and OVERTR_EGENKAP<.25 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 26 ;
GRP_OVERTR_EGENKAP = 29898;
end;

else if OVERTR_EGENKAP>=.25 and OVERTR_EGENKAP<2.4 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 17 ;
GRP_OVERTR_EGENKAP = 29899;
end;

else if OVERTR_EGENKAP>=2.4 and OVERTR_EGENKAP<7.35 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 13 ;
GRP_OVERTR_EGENKAP = 29900;
end;

else if OVERTR_EGENKAP>=7.35 and OVERTR_EGENKAP<19.8000 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 7 ;
GRP_OVERTR_EGENKAP = 29895;
end;

else if OVERTR_EGENKAP >=19.8000 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_OVERTR_EGENKAP = 29901;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_OVERTR_EGENKAP = 29901;
end;
end;
else if MISSING(OVERTR_EGENKAP) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_OVERTR_EGENKAP = 29901;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_OVERTR_EGENKAP = 29901;
end;


*------------------------------------------------------------*;
* Variable: TRANS_LIM_EGENKAP;
*------------------------------------------------------------*;
if  NOT MISSING(TRANS_LIM_EGENKAP) then do;
if TRANS_LIM_EGENKAP>=0 and TRANS_LIM_EGENKAP<=0 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 26 ;
GRP_TRANS_LIM_EGENKAP = 29909;
end;

else if TRANS_LIM_EGENKAP >0 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 5 ;
GRP_TRANS_LIM_EGENKAP = 29910;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_TRANS_LIM_EGENKAP = 29911;
end;
end;
else if MISSING(TRANS_LIM_EGENKAP) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_TRANS_LIM_EGENKAP = 29911;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_TRANS_LIM_EGENKAP = 29911;
end;


*------------------------------------------------------------*;
* Variable: UDLAAN_SUM_EGENKAP;
*------------------------------------------------------------*;
if  NOT MISSING(UDLAAN_SUM_EGENKAP) then do;
if UDLAAN_SUM_EGENKAP <-245 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 5 ;
GRP_UDLAAN_SUM_EGENKAP = 29920;
end;

else if UDLAAN_SUM_EGENKAP>=-245 and UDLAAN_SUM_EGENKAP<-35 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 21 ;
GRP_UDLAAN_SUM_EGENKAP = 29921;
end;

else if UDLAAN_SUM_EGENKAP>=-35 and UDLAAN_SUM_EGENKAP<-10 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 33 ;
GRP_UDLAAN_SUM_EGENKAP = 29922;
end;

else if UDLAAN_SUM_EGENKAP>=-10 and UDLAAN_SUM_EGENKAP<=0 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 43 ;
GRP_UDLAAN_SUM_EGENKAP = 29923;
end;

else if UDLAAN_SUM_EGENKAP >0 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_UDLAAN_SUM_EGENKAP = 29924;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_UDLAAN_SUM_EGENKAP = 29924;
end;
end;
else if MISSING(UDLAAN_SUM_EGENKAP) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_UDLAAN_SUM_EGENKAP = 29924;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_UDLAAN_SUM_EGENKAP = 29924;
end;

SCORECARD_POINTS = EM_SCORECARD_POINTS;
run;
