data &m_output_table_nm;
set &m_scoring_abt_table_nm;

*------------------------------------------------------------*;
* DABT JUDGEMENTAL SCORE CODE;
*------------------------------------------------------------*;

EM_SCORECARD_POINTS = 0;

*------------------------------------------------------------*;
* Variable: UDNYTSEGRAD_KREDIT_MEAN_3MND;
*------------------------------------------------------------*;
if  NOT MISSING(UDNYTSEGRAD_KREDIT_MEAN_3MND) then do;
if UDNYTSEGRAD_KREDIT_MEAN_3MND <25 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 136 ;
GRP_UDNYTSEGRAD_KREDIT_MEAN_3MND = 32546;
end;

else if UDNYTSEGRAD_KREDIT_MEAN_3MND>=25 and UDNYTSEGRAD_KREDIT_MEAN_3MND<55 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 93 ;
GRP_UDNYTSEGRAD_KREDIT_MEAN_3MND = 32547;
end;

else if UDNYTSEGRAD_KREDIT_MEAN_3MND>=55 and UDNYTSEGRAD_KREDIT_MEAN_3MND<80 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 82 ;
GRP_UDNYTSEGRAD_KREDIT_MEAN_3MND = 32548;
end;

else if UDNYTSEGRAD_KREDIT_MEAN_3MND>=80 and UDNYTSEGRAD_KREDIT_MEAN_3MND<85 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 71 ;
GRP_UDNYTSEGRAD_KREDIT_MEAN_3MND = 32549;
end;

else if UDNYTSEGRAD_KREDIT_MEAN_3MND>=85 and UDNYTSEGRAD_KREDIT_MEAN_3MND<95 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 60 ;
GRP_UDNYTSEGRAD_KREDIT_MEAN_3MND = 32550;
end;

else if UDNYTSEGRAD_KREDIT_MEAN_3MND>=95 and UDNYTSEGRAD_KREDIT_MEAN_3MND<100 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 46 ;
GRP_UDNYTSEGRAD_KREDIT_MEAN_3MND = 32551;
end;

else if UDNYTSEGRAD_KREDIT_MEAN_3MND>=100 and UDNYTSEGRAD_KREDIT_MEAN_3MND<110 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 19 ;
GRP_UDNYTSEGRAD_KREDIT_MEAN_3MND = 32552;
end;

else if UDNYTSEGRAD_KREDIT_MEAN_3MND >=110 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_UDNYTSEGRAD_KREDIT_MEAN_3MND = 32553;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 56 ;
GRP_UDNYTSEGRAD_KREDIT_MEAN_3MND = 32554;
end;
end;
else if MISSING(UDNYTSEGRAD_KREDIT_MEAN_3MND) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 56 ;
GRP_UDNYTSEGRAD_KREDIT_MEAN_3MND = 32554;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 56 ;
GRP_UDNYTSEGRAD_KREDIT_MEAN_3MND = 32554;
end;


*------------------------------------------------------------*;
* Variable: AVG_INDLAAN_ENGAGEMENT;
*------------------------------------------------------------*;
if  NOT MISSING(AVG_INDLAAN_ENGAGEMENT) then do;
if AVG_INDLAAN_ENGAGEMENT <5 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_AVG_INDLAAN_ENGAGEMENT = 32543;
end;

else if AVG_INDLAAN_ENGAGEMENT>=5 and AVG_INDLAAN_ENGAGEMENT<20 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 14 ;
GRP_AVG_INDLAAN_ENGAGEMENT = 32544;
end;

else if AVG_INDLAAN_ENGAGEMENT >=20 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 31 ;
GRP_AVG_INDLAAN_ENGAGEMENT = 32545;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_AVG_INDLAAN_ENGAGEMENT = 32543;
end;
end;
else if MISSING(AVG_INDLAAN_ENGAGEMENT) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_AVG_INDLAAN_ENGAGEMENT = 32543;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_AVG_INDLAAN_ENGAGEMENT = 32543;
end;


*------------------------------------------------------------*;
* Variable: MIN_KREDOMS_AVG_KREDOMS;
*------------------------------------------------------------*;
if  NOT MISSING(MIN_KREDOMS_AVG_KREDOMS) then do;
if MIN_KREDOMS_AVG_KREDOMS <5 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_MIN_KREDOMS_AVG_KREDOMS = 32555;
end;

else if MIN_KREDOMS_AVG_KREDOMS>=5 and MIN_KREDOMS_AVG_KREDOMS<60 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 15 ;
GRP_MIN_KREDOMS_AVG_KREDOMS = 32556;
end;

else if MIN_KREDOMS_AVG_KREDOMS >=60 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 33 ;
GRP_MIN_KREDOMS_AVG_KREDOMS = 32557;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_MIN_KREDOMS_AVG_KREDOMS = 32555;
end;
end;
else if MISSING(MIN_KREDOMS_AVG_KREDOMS) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_MIN_KREDOMS_AVG_KREDOMS = 32555;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_MIN_KREDOMS_AVG_KREDOMS = 32555;
end;


*------------------------------------------------------------*;
* Variable: UDLAAN_SUM_EGENKAP;
*------------------------------------------------------------*;
if  NOT MISSING(UDLAAN_SUM_EGENKAP) then do;
if UDLAAN_SUM_EGENKAP <-500 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 8 ;
GRP_UDLAAN_SUM_EGENKAP = 32583;
end;

else if UDLAAN_SUM_EGENKAP>=-500 and UDLAAN_SUM_EGENKAP<-200 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 15 ;
GRP_UDLAAN_SUM_EGENKAP = 32584;
end;

else if UDLAAN_SUM_EGENKAP>=-200 and UDLAAN_SUM_EGENKAP<-100 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 20 ;
GRP_UDLAAN_SUM_EGENKAP = 32585;
end;

else if UDLAAN_SUM_EGENKAP>=-100 and UDLAAN_SUM_EGENKAP<-30 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 24 ;
GRP_UDLAAN_SUM_EGENKAP = 32586;
end;

else if UDLAAN_SUM_EGENKAP>=-30 and UDLAAN_SUM_EGENKAP<=0 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 67 ;
GRP_UDLAAN_SUM_EGENKAP = 32587;
end;

else if UDLAAN_SUM_EGENKAP >0 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_UDLAAN_SUM_EGENKAP = 32588;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 19 ;
GRP_UDLAAN_SUM_EGENKAP = 32589;
end;
end;
else if MISSING(UDLAAN_SUM_EGENKAP) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 19 ;
GRP_UDLAAN_SUM_EGENKAP = 32589;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 19 ;
GRP_UDLAAN_SUM_EGENKAP = 32589;
end;


*------------------------------------------------------------*;
* Variable: UDLAAN_SUM_EBITDA;
*------------------------------------------------------------*;
if  NOT MISSING(UDLAAN_SUM_EBITDA) then do;
if UDLAAN_SUM_EBITDA <-300 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 4 ;
GRP_UDLAAN_SUM_EBITDA = 32576;
end;

else if UDLAAN_SUM_EBITDA>=-300 and UDLAAN_SUM_EBITDA<-200 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 19 ;
GRP_UDLAAN_SUM_EBITDA = 32577;
end;

else if UDLAAN_SUM_EBITDA>=-200 and UDLAAN_SUM_EBITDA<-75 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 26 ;
GRP_UDLAAN_SUM_EBITDA = 32578;
end;

else if UDLAAN_SUM_EBITDA>=-75 and UDLAAN_SUM_EBITDA<-20 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 37 ;
GRP_UDLAAN_SUM_EBITDA = 32579;
end;

else if UDLAAN_SUM_EBITDA>=-20 and UDLAAN_SUM_EBITDA<=0 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 85 ;
GRP_UDLAAN_SUM_EBITDA = 32580;
end;

else if UDLAAN_SUM_EBITDA >0 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_UDLAAN_SUM_EBITDA = 32581;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 34 ;
GRP_UDLAAN_SUM_EBITDA = 32582;
end;
end;
else if MISSING(UDLAAN_SUM_EBITDA) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 34 ;
GRP_UDLAAN_SUM_EBITDA = 32582;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 34 ;
GRP_UDLAAN_SUM_EBITDA = 32582;
end;


*------------------------------------------------------------*;
* Variable: AVG_DEBOMS_AVG_KREDOMS;
*------------------------------------------------------------*;
if  NOT MISSING(AVG_DEBOMS_AVG_KREDOMS) then do;
if AVG_DEBOMS_AVG_KREDOMS <98 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 622 ;
GRP_AVG_DEBOMS_AVG_KREDOMS = 32538;
end;

else if AVG_DEBOMS_AVG_KREDOMS>=98 and AVG_DEBOMS_AVG_KREDOMS<100 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 612 ;
GRP_AVG_DEBOMS_AVG_KREDOMS = 32539;
end;

else if AVG_DEBOMS_AVG_KREDOMS>=100 and AVG_DEBOMS_AVG_KREDOMS<110 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 584 ;
GRP_AVG_DEBOMS_AVG_KREDOMS = 32540;
end;

else if AVG_DEBOMS_AVG_KREDOMS>=110 and AVG_DEBOMS_AVG_KREDOMS<125 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 578 ;
GRP_AVG_DEBOMS_AVG_KREDOMS = 32541;
end;

else if AVG_DEBOMS_AVG_KREDOMS >=125 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 565 ;
GRP_AVG_DEBOMS_AVG_KREDOMS = 32542;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 565 ;
GRP_AVG_DEBOMS_AVG_KREDOMS = 32542;
end;
end;
else if MISSING(AVG_DEBOMS_AVG_KREDOMS) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 565 ;
GRP_AVG_DEBOMS_AVG_KREDOMS = 32542;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 565 ;
GRP_AVG_DEBOMS_AVG_KREDOMS = 32542;
end;


*------------------------------------------------------------*;
* Variable: OVERTRK_MAX_AKT_MAX_6MND;
*------------------------------------------------------------*;
if  NOT MISSING(OVERTRK_MAX_AKT_MAX_6MND) then do;
if OVERTRK_MAX_AKT_MAX_6MND>=0 and OVERTRK_MAX_AKT_MAX_6MND<=0 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 100 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 32568;
end;

else if OVERTRK_MAX_AKT_MAX_6MND>0 and OVERTRK_MAX_AKT_MAX_6MND<6 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 75 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 32569;
end;

else if OVERTRK_MAX_AKT_MAX_6MND>=6 and OVERTRK_MAX_AKT_MAX_6MND<13 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 54 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 32570;
end;

else if OVERTRK_MAX_AKT_MAX_6MND>=13 and OVERTRK_MAX_AKT_MAX_6MND<31 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 47 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 32571;
end;

else if OVERTRK_MAX_AKT_MAX_6MND>=31 and OVERTRK_MAX_AKT_MAX_6MND<46 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 27 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 32572;
end;

else if OVERTRK_MAX_AKT_MAX_6MND>=46 and OVERTRK_MAX_AKT_MAX_6MND<61 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 21 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 32573;
end;

else if OVERTRK_MAX_AKT_MAX_6MND>=61 and OVERTRK_MAX_AKT_MAX_6MND<91 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 8 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 32574;
end;

else if OVERTRK_MAX_AKT_MAX_6MND >=91 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 32575;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 100 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 32568;
end;
end;
else if MISSING(OVERTRK_MAX_AKT_MAX_6MND) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 100 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 32568;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 100 ;
GRP_OVERTRK_MAX_AKT_MAX_6MND = 32568;
end;


*------------------------------------------------------------*;
* Variable: OVERTR_EGENKAP;
*------------------------------------------------------------*;
if  NOT MISSING(OVERTR_EGENKAP) then do;
if OVERTR_EGENKAP <-10 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 0 ;
GRP_OVERTR_EGENKAP = 32558;
end;

else if OVERTR_EGENKAP>=-10 and OVERTR_EGENKAP<-3 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 23 ;
GRP_OVERTR_EGENKAP = 32559;
end;

else if OVERTR_EGENKAP>=-3 and OVERTR_EGENKAP<-1 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 35 ;
GRP_OVERTR_EGENKAP = 32560;
end;

else if OVERTR_EGENKAP>=-1 and OVERTR_EGENKAP<-0.1 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 43 ;
GRP_OVERTR_EGENKAP = 32561;
end;

else if OVERTR_EGENKAP>=-0.1 and OVERTR_EGENKAP<0 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 66 ;
GRP_OVERTR_EGENKAP = 32562;
end;

else if OVERTR_EGENKAP>=0 and OVERTR_EGENKAP<0.2 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 108 ;
GRP_OVERTR_EGENKAP = 32563;
end;

else if OVERTR_EGENKAP>=0.2 and OVERTR_EGENKAP<2 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 72 ;
GRP_OVERTR_EGENKAP = 32564;
end;

else if OVERTR_EGENKAP>=2 and OVERTR_EGENKAP<10 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 46 ;
GRP_OVERTR_EGENKAP = 32565;
end;

else if OVERTR_EGENKAP >=10 then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 20 ;
GRP_OVERTR_EGENKAP = 32566;
end;

else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 49 ;
GRP_OVERTR_EGENKAP = 32567;
end;
end;
else if MISSING(OVERTR_EGENKAP) then do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 49 ;
GRP_OVERTR_EGENKAP = 32567;
end;
else do;
EM_SCORECARD_POINTS = EM_SCORECARD_POINTS + 49 ;
GRP_OVERTR_EGENKAP = 32567;
end;

SCORECARD_POINTS = EM_SCORECARD_POINTS;
run;
