/* cas mySession terminate; */
cas mySession sessopts=(timeout=3500000);
caslib _all_ assign;
options casdatalimit=20000M;

/*  %LET START_PERIODAG = 2018-03-01;   */
/*  %LET SLUT_PERIODAG = 2023-01-31;   */

/* %LET START_PERIODAG = 2022-02-01;  */
/* %LET SLUT_PERIODAG = 2022-04-10;  */

/* %LET SQL_START_PERIODAG=%STR(%')&START_PERIODAG.%STR(%'); */
/* %LET SQL_SLUT_PERIODAG=%STR(%')&SLUT_PERIODAG.%STR(%'); */

/*Finder engagement på delmodparts niveau  */
PROC FEDSQL SESSREF=mySession;
drop table CASUSER.STAMOPL_ENGA FORCE;
CREATE TABLE CASUSER.STAMOPL_ENGA AS SELECT 
DEL_MODPARTS_ID
,START_DATO
,SLUT_DATO
,SUM(ENGAGEMENT_KREDIT) AS DELMODPART_ENGAGEMENT_KREDIT

FROM RAT_DATA.STAMOPLYSNINGER

GROUP BY DEL_MODPARTS_ID, START_DATO, SLUT_DATO
;
QUIT; 

/* Joiner  */
PROC FEDSQL SESSREF=mySession;
drop table CASUSER.STAMOPLYSNINGER FORCE;
CREATE TABLE CASUSER.STAMOPLYSNINGER AS SELECT 
STAM.*
,ENGA.DELMODPART_ENGAGEMENT_KREDIT

FROM RAT_DATA.STAMOPLYSNINGER AS STAM

LEFT JOIN CASUSER.STAMOPL_ENGA AS ENGA
ON STAM.DEL_MODPARTS_ID=ENGA.DEL_MODPARTS_ID AND STAM.START_DATO=ENGA.START_DATO AND STAM.SLUT_DATO=ENGA.SLUT_DATO 
;
QUIT; 


/*Uploader til RAT_DATA  */
%LET VIYA_LIBRARY=RAT_DATA; 
%LET TABEL_NAVN=STAMOPLYSNINGER; 

	proc casutil  incaslib="casuser" outcaslib="&VIYA_LIBRARY." ;    
		save casdata="&TABEL_NAVN." replace; 
		DROPTABLE CASDATA="&TABEL_NAVN." INCASLIB="&VIYA_LIBRARY." QUIET;
		load casdata="&TABEL_NAVN..sashdat" 
		casout="&TABEL_NAVN." 	
		incaslib="&VIYA_LIBRARY."  promote;
	run;



