

PROC FEDSQL SESSREF=mySession;
drop table casuser.test FORCE;
CREATE TABLE casuser.test AS SELECT 
START_DATO,
MEDIAN(Formue_netto) AS test
FROM RAT_DATA.OKONOMI_KORR_TRANS

GROUP BY START_DATO
;
QUIT;

PROC SQL ;
SELECT 
NAME
,NAME
,COUNT(NAME)
INTO
	: VARS SEPARATED BY " "
	,: VAR_1-
	,: ANTAL
FROM SASHELP.VCOLUMN
WHERE LIBNAME = "RAT_DATA"
AND MEMNAME = "OKONOMI_KORR_TRANS"
AND TYPE="num"
AND FORMAT NOT IN ("DATE9.","DATETIME20.")
;
QUIT;
%PUT &VARS. &ANTAL. &VAR_1. &VAR_2.;



%macro LOOP;

%DO I=1 %TO 2; 
/* %DO I=1 TO &ANTAL;  */

proc univariate data = RAT_DATA.OKONOMI_KORR_TRANS noprint;
var &&VAR_&I..;
output out=QUARTILES_&I. PCTLPTS = 25 75 PCTLPRE = _ ;
run;

PROC TRANSPOSE DATA=QUARTILES_&I. OUT=QUARTILES_TRANS_&I.; RUN;

DATA CASUSER.QUARTILES_TRANS_&I.( REPLACE=yes); 
SET QUARTILES_TRANS_&I.;
length name $50;
COL_NAME="&&VAR_&I..";
DOUBLEVALUE=COL1; 
IF _NAME_="_25" THEN ROWID=25;
ELSE IF _NAME_="_75" THEN ROWID=75;
CHAR_VALUE=_LABEL_;

KEEP COL_NAME DOUBLEVALUE ROWID CHAR_VALUE;
RUN; 
%END; 



DATA CASUSER.QUARTILES( REPLACE=yes);  ; 
SET 
%DO I=1 %TO 2; 
	CASUSER.QUARTILES_TRANS_&I.
%END;
;
RUN; 

%MEND; 
%LOOP








data casuser.&FUNKTION. ( REPLACE=yes);
set &FUNKTION. (rename=(_NAME_ = COL_NAME COL1 = DoubleValue));
RowID = &ROWID.; 
CharValue = "&FUNKTION.";
run;